### ISSUE TITLE
SSLError raised

### ISSUE THREAD

**Issue by npip99** [Kylmakalle/mixpanel-python-asyncio#2]
I commonly get this error on execution,

```python
Traceback (most recent call last):
  File "/Users/gguest/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/sslproto.py", line 648, in _do_shutdown
    self._sslobj.unwrap()
  File "/Users/gguest/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 921, in unwrap
    return self._sslobj.shutdown()
           ^^^^^^^^^^^^^^^^^^^^^^^
ssl.SSLError: [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2685)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/mixpanel_asyncio/__init__.py", line 631, in _write_request
    response = await client.post(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/aiohttp_retry/client.py", line 149, in __aenter__
    return await self._do_request()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/aiohttp_retry/client.py", line 138, in _do_request
    raise e
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/aiohttp_retry/client.py", line 100, in _do_request
    response: ClientResponse = await self._request_func(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 976, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/aiohttp/streams.py", line 640, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2685)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gguest/Documents/testing/backend/routes/logging.py", line 181, in analytics_event
    await mp.track(str(user_id), event_name, properties)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/mixpanel_asyncio/__init__.py", line 105, in track
    await self._consumer.send("events", json_dumps(event, cls=self._serializer))
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/mixpanel_asyncio/__init__.py", line 607, in send
    await self._write_request(self._endpoints[endpoint], json_message, api_key, api_secret)
  File "/Users/gguest/Documents/testing/backend/.venv/lib/python3.12/site-packages/mixpanel_asyncio/__init__.py", line 638, in _write_request
    raise MixpanelException from e
mixpanel_asyncio.MixpanelException
```

This is easily resolvable by the caller by doing,

```python
    NUM_TRIES = 5
    for i in range(NUM_TRIES):
        try:
            await mp.track(str(user_id), event_name, properties)
            return GenericMessageResponse(message="Success!")
        except MixpanelException as e:
            await asyncio.sleep(5)
            if i == NUM_TRIES - 1:
                logger.error(repr(e))

    raise HTTPException(status_code=500, detail="Could not fulfill your request")
```

In my testing, the error never made it past 5 tries. Maybe this can be part of Mixpanel's internal "try again" loop.

## Hardware

```
      Model Name: MacBook Pro
      Model Identifier: Mac15,6
      Model Number: MRX33LL/A
      Chip: Apple M3 Pro
      Total Number of Cores: 11 (5 performance and 6 efficiency)
      Memory: 18 GB
      System Firmware Version: 10151.81.1
      OS Loader Version: 10151.81.1
```

**Comment by Kylmakalle** [comment]
@npip99 So the app keep sending data, even tho aiohttp connection was closed either due to local reasons or weird remote. I've never experienced that in my apps. But seing you have "solved" it with a retry loop, I'd assume it's something about Mixpanel endpoints that may be rejecting connections sometimes.

These days I'm creating aiohttp sessions like this and haven't seesn any issues like that with other APIs. Might be helpfull for anybody who'll be passing by

```python
import asyncio
import ssl
from typing import Any, AsyncGenerator, Dict, Optional, Type
from types import TracebackType

import certifi
from aiohttp import ClientSession, TCPConnector


class AiohttpSessionManager:
    def __init__(self) -> None:
        self._session: Optional[ClientSession] = None
        self._connector_type: Type[TCPConnector] = TCPConnector
        self._connector_init: Dict[str, Any] = {
            "ssl": ssl.create_default_context(cafile=certifi.where()),
        }
        self._should_reset_connector = True  # flag determines connector state

    async def get_or_create_session(self) -> ClientSession:
        if self._should_reset_connector:
            await self.close()

        if self._session is None or self._session.closed:
            self._session = ClientSession(connector=self._connector_type(**self._connector_init))
            self._should_reset_connector = False

        return self._session

    async def close(self) -> None:
        if self._session is not None and not self._session.closed:
            await self._session.close()

            # Wait 250 ms for the underlying SSL connections to close
            # https://docs.aiohttp.org/en/stable/client_advanced.html#graceful-shutdown
            await asyncio.sleep(0.25)
```
